<%@ Page Title="" Language="C#" MasterPageFile="~/views/inventario.Master" AutoEventWireup="true" CodeBehind="Operaciones.aspx.cs" Inherits="Web_Presentation.views.Operaciones.Operaciones" %>
<asp:Content ID="Content1" ContentPlaceHolderID="head" runat="server">
</asp:Content>
<asp:Content ID="Content2" ContentPlaceHolderID="ContentPlaceHolder1" runat="server">
        <div class="container" style="margin-top:5%">
        <div class="card alert alert-secondary">
          <h5 class="card-header">Operaciones a las tablas (Eliminar)</h5>
          <div class="card-body">
            <h6 class="card-title">
                    Seleccione una opcion de la siguiente lista para realizar las tareas necesarias
            </h6>
            <p class="card-text">
               Opciones: <asp:DropDownList ID="Query" class="btn btn-secondary dropdown-toggle" runat="server"></asp:DropDownList>
               
            </p>

            <asp:Button ID="Consultar" OnClick="Consultar_Click"  runat="server" CssClass=" btn btn-success" Text="Consultar" />

          </div>
        </div>
        <div class="container" style="margin-bottom:5%">
            <div class="row text-center" >
                <h4>
                    <asp:Label ID="Label1" runat="server" Text=""></asp:Label></h4>
            </div>
            <div class="row ">
                <asp:HiddenField ID="HiddenField1" runat="server"/>  
                <asp:GridView ID="GridView1" OnRowDeleting="GridView1_RowDeleting"  AutoGenerateDeleteButton="true" 
                      class="table table-dark table-striped" runat="server">
                        </asp:GridView>
            </div>
        </div>
    </div>
</asp:Content>
