<%@ Page Title="" Language="C#" MasterPageFile="~/views/inventario.Master" AutoEventWireup="true" CodeBehind="Operaciones.aspx.cs" Inherits="Web_Presentation.views.Operaciones.Operaciones" %>
<asp:Content ID="Content1" ContentPlaceHolderID="head" runat="server">
</asp:Content>
<asp:Content ID="Content2" ContentPlaceHolderID="ContentPlaceHolder1" runat="server">
        <div class="container" style="margin-top:5%">
        <div class="card alert alert-secondary">
          <h5 class="card-header">Operaciones a las tablas (Eliminar y Editar)</h5>
          <div class="card-body">
            <h6 class="card-title">
                    Seleccione una opcion de la siguiente lista para realizar las tareas necesarias
            </h6>
            <p class="card-text">
               Opciones: <asp:DropDownList ID="Query" class="btn btn-secondary dropdown-toggle" runat="server"></asp:DropDownList>
               
            </p>
              <%--<div class="alert alert-danger  d-flex align-items-center" runat="server" id="Alerta" role="alert">
                  <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" fill="currentColor" class="bi bi-exclamation-triangle-fill flex-shrink-0 me-2" viewBox="0 0 16 16" role="img" aria-label="Warning:">
                    <path d="M8.982 1.566a1.13 1.13 0 0 0-1.96 0L.165 13.233c-.457.778.091 1.767.98 1.767h13.713c.889 0 1.438-.99.98-1.767L8.982 1.566zM8 5c.535 0 .954.462.9.995l-.35 3.507a.552.552 0 0 1-1.1 0L7.1 5.995A.905.905 0 0 1 8 5zm.002 6a1 1 0 1 1 0 2 1 1 0 0 1 0-2z"/>
                  </svg>
                  <div>
                    Seleccione un tipo de monitor!!
                  </div>
               </div>--%>
            <asp:Button ID="Consultar" OnClick="Consultar_Click"  runat="server" CssClass=" btn btn-success" Text="Consultar" />

          </div>
        </div>
        <div class="container" style="margin-bottom:5%">
            <div class="row text-center" >
                <h4>
                    <asp:Label ID="Label1" runat="server" Text=""></asp:Label></h4>
            </div>
            <div class="row ">
                <asp:HiddenField ID="HiddenField1" runat="server"/>  
                <asp:GridView ID="GridView1" OnRowDeleting="GridView1_RowDeleting" AutoGenerateDeleteButton="true" 
                    AutoGenerateEditButton="true" OnRowCancelingEdit="GridView1_RowCancelingEdit" OnRowEditing="GridView1_RowEditing"  class="table table-dark table-striped" runat="server">
                        </asp:GridView>
            </div>
        </div>
    </div>
</asp:Content>
